<section id="content-generation">
<h2 class="heading-1">7. Content Generation</h2>
<p>The subject matter of all content generation must be relevant, congruent with our <a href="#voice" data-emoji="anchor">Voice</a> and <a href="#tone" data-emoji="anchor">Tone</a>, and in touch with reality. We don't want to be <a href="https://www.reddit.com/r/LinkedInLunatics/" target="_blank" rel="nofollow" title="reddit.com/r/linkedinlunatics" data-emoji="link">r/LinkedInLunatics</a>. We aim to publish content frequently, yes; But, never at the expense of quality.</p>
<h3 id="newsletter" class="heading-2">7.1. Newsletter</h3>
<p>The Newsletter is the holy grail of our content strategy. It allows us to focus on short-form content delivered directly to our subscribers in their inbox.</p>
<p>Most Blogs out there demand a lot of resources to end up with a very long, elaborate, polished post, that none or very few people read in full. Our Newsletter prioritizes an efficient content creation workflow that results in easily degistible content published frequently and consistently.</p>
<p>The content produced for the Newsletter is repurposed in two ways. (A) as Social Media posts in LinkedIn, and (B) kept in an online archive as a page in <a data-before="plfn" href="https://polyfen.com/newsletter" target="_blank" rel="dofollow">Polyfen's</a> website.</p>
<p>The purpose of the Newsletter is not to push sales of our services blatantly. The goal is to provide our followers with valuable information about the industry.</p>
<h4 class="heading-3" id="subject">Subject</h4>
<ul class="hanging-list">
    <li>Start with an emoji to illustrate the topic.</li>
    <li>Keep the length under 70 characters.</li>
    <li>Set the text in Title-Casing.</li>
    <li>Be descriptive. Avoid click-baity subjects.</li>
</ul>
<p>Examples:</p>
<ul class="hanging-list">
    <li>💰 How Branding Makes you Money</li>
    <li>🤖 You Should Have an AI Ethics Policy</li>
    <li>🧪 How our Small Team Invests in R&D</li>
    <li>📕 How to Write Useful Brand Guidelines</li>
</ul>
<h4 class="heading-3" id="body-text">Preview Text</h4>
<ul class="hanging-list">
    <li>Engage the user with a sub-title to the subject line.</li>
    <li>Max 150 characters.</li>
</ul>
<p>Example</p>
<div class="preview">
    <p class="align-left" style="font-style: italic;">Ever wondered why Coca-Cola is worth 260 billion? How about Apple being worth 2.65 trillion? </p>
</div>
<h4 class="heading-3" id="image">Image</h4>
<p>Start the email message with a cover image.</p>
<ul class="hanging-list">
    <li>Dimensions: 1200px × 630px</li>
    <li>Format: JPG</li>
</ul>
<p>Example:</p>
<img src="imgs/email-image-example.jpg">
<h4 class="heading-3" id="body-text">Body Text</h4>
<ul class="hanging-list">
    <li>Ideally 3-5 paragraphs long.</li>
    <li>Finish the message with a link to our LinkedIn page.</li>
</ul>
<p>Example</p>
<div class="preview">
    <p style="text-align:left;font-style:italic;">Ever wonder why Coca-Cola is worth 260 billion? How about Apple being worth 2.65 trillion? The price of those companies shares is a direct reflection of their ability to do good Branding.</p>
    <p style="text-align:left;font-style:italic;">Investing in your Brand (name, logo, website, social media profiles) makes your business money in three ways:</p>
    <p style="text-align:left;font-style:italic;">1. Higher Market-Share<br>A consumer faced with multiple buying options in a similar price range will always choose the most professional, trust-worthy-looking seller. Packaging what you offer with an eye-catching logo, a memorable brand name, an elegant design will lead more buyers away from your competitors and towards your pocket.</p>
    <p style="text-align:left;font-style:italic;">2. Higher Pricing<br>Once you’ve gained portion of the Market-Share...</p>
    <p style="text-align:left;font-style:italic;">3. Higher Company Valuation<br>If you were to buy 100% of shares of The Coca-Cola Company, you would be paying for ownership of (A) the Upside Potential (income from future sales generated by the company), (B) their Tangible Assets (manufacturing plants, vehicles, inventory of ingredients, …), and (B) their Intangible Assets, like the intellectual property of the Brand Identity (brand name, …)....</p>
</div>
<h4 class="heading-3" id="newsletter-signature">Signature</h4>
<div class="preview">
<p style="text-align:left;font-style:italic;">Join the conversation about [EMAIL TOPIC] in our <a href="https://www.linkedin.com/company/polyfen/mycompany/?viewAsMember=true" target="_blank">LinkedIn Page</a> and share your thoughts.</p>
<p style="text-align:left;font-style:italic;">
    Boris Hrnčić<br>
    Founder &amp; CEO<br>
    <a href="https://linkedin.com/in/borishr" target="_blank">Connect on LinkedIn</a><br>
    <a href="https://polyfen.com/?utm_source=signature&utm_medium=email&utm_campaign=newsletter" target="_blank">polyfen.com</a><br>
</p>
</div>
<h4 class="heading-3" id="newsletter-design">Design</h4>
<p>The design of the Newsletter template is purposefully as simple and clean as possible. It relies on color and typography to tie it in with our Brand Identity. All other aspects of the design should resemble a plain text email sent to you by a colleague. We must stay away from overly complex layouts and heavy use of visuals. Our Newsletter's strength lies in producing real, valuable content, sent to you by a person.</p>
<img src="imgs/newsletter-design.png" alt="">
<h3 id="social-media" class="heading-2">7.2. Social Media</h3>
</section>